config/routes.rb
Rails.application.routes.draw do
  root "pins#index"
  devise_for :users

  resources :pins do
    collection do
      get 'search'
    end
    member do
      put "Lile", to: "pins#upvote"
    end
  end

  resources :tags, only: [:show]
  resources :categories, only: [:show]

  namespace :admin do
    resources :pins, except: [:show, :index]
    resources :categories, except: [:show]
  end

  get ':username' => 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :pins
  validates :name, presence: true

  has_ancestry
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  searchkick
  acts_as_votable
  belongs_to :user
  belongs_to :category

  has_attached_file :image, styles: { medium: "600x600>", thumb: "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/



  has_many :taggings, dependent: :delete_all
  has_many :tags, through: :taggings

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(', ').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :pins, through: :taggings

  def self.counts
    # self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
    all.each_with_object({}) { |t, memo| memo[t.name] = t.taggings.map(&:tag_id).count if t.taggings.count > 0 }.sort_by(&:last).reverse.to_h
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :pin
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  validates_uniqueness_of :username

  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "200x200>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected

  def check_admin
    binding.pry
    redirect_to root_path, alert: "You do not have permission to access this page" unless current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:edit, :update, :destroy]
  before_action :check_admin

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория успешно создана'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория успешно обновлена'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: 'Категория успешно удалена'
  end

  protected

  def check_admin
    redirect_to root_path, alert: "You do not have permission to access this page" unless current_user.admin?
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/admin/pins_controller.rb
class Admin::PinsController < ApplicationController
  before_action :find_pin, only: [:edit, :update, :destroy, :upvote]
  before_action :authenticate_user!
  before_action :check_admin

  def search
    if params[:search].present?
      @pins = Pin.search(params[:search])
    else
      @pins = Pin.all
    end
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Seccessfully created new Pin"
    else
      render 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully update!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  protected

  def check_admin
    redirect_to root_path, alert: "You do not have permission to access this page" unless current_user.admin?
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image, :all_tags, :category_id)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :avatar, :image])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @pins = Pin.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 7)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    if params[:search].present?
      @pins = Pin.search(params[:search])
    else
      @pins = Pin.all
    end
  end

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Seccessfully created new Pin"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was Successfully update!"
    else
      render 'edit'
    end
  end

  def destroy
    @pins.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image, :all_tags)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by(name: params[:id])
    @pins = @tag.pins
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper

  def tag_cloud(tags, classes)
    max = tags.values.max
    tags.each do |tag, value|
      index = value.to_f / max * (classes.size - 1)
      yield(Tag.find_by_name(tag), classes[index.round])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [ :admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to "Back", :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1>Category</h1>

<div class="buttons_panel">
  <%= link_to 'Новая категория', new_admin_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name </th>
        <th>Category parent</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= category.name %></td>
          <td><%= category.parent.name if category.parent.present? %></td>
          <td>
            <%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm'  %>
            <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-outline-danger btn-sm'  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/categories/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Create A New Category</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? t('common.create'): t('common.edit')), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/pins/_form.html.erb
<%= simple_form_for [:admin, @pin], html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors"></div>
    <h2></h2>
    <%= pluralize(@pin.errors.count, "error") %>
    prevented this Pin from saving
    <ul>
      <% @pin.errors.ful_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="form_group">
    <%= f.input :image, input_html: { class: 'form-control' } %>
  </div>

  <div class="form_group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>

  <div class="form_group">
    <%= f.input :all_tags, input_html: { class: 'form-control' } %>
  </div>

  <div class="form_group">
    <%= f.input :category_id, input_html: { class: 'form-control' } %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form_group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/pins/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Your Pin</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Current Image</strong>
          <%= image_tag @pin.image.url(:medium) %>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/pins/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Create A New Pin</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [ @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to "Back", :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1> Edit</h1>

<%= render 'form' %>

app/views/categories/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Create A New Category</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<%= will_paginate @pins, renderer: 'BootstrapPaginationeHelper::LinkRenderer' %>

<h1><%= @category.name %></h1>

<% if @category.pins.empty? %>
  <h2>Статей нет</h2>
<% end %>


<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url(:thumb)), pin %>

      <div class="panel-body">
        <h2><%= link_to pin.title, pin %></h2>
        <p>
         <small>
            <time><%= pin.created_at.to_date.strftime("%d %B, %Y") %></time>
          </small>
        </p>
        <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
        <p><%= pin.description %></p>
        <% if pin.user == current_user %>
        <% end %>

        <p class="user"></p>
        Submitted by
        <%= pin.user.email %>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html></html>
<header>
  <title>Shuttersbank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</header>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Shuttersbank", root_path %>
      </div>
        <% if user_signed_in? %>
          <ul class='nav navbar-nav navbar-left' style="margin-top: 8px;">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Categories
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to('Category settings', admin_categories_path, { tabindex: '-1' })%></li>
                <% end %>
                <% Category.where(ancestry: nil).each do |category| %>
                  <% if category.children.blank? %>
                    <li><a tabindex="-1" href="#"><%= "#{category.name}"%></a></li>
                  <% else %>
                    <li class="dropdown-submenu">
                      <a class="test" tabindex="-1" href="#"><%= "#{category.name}"%><span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <% category.children.each do |child| %>
                          <% if current_user.admin? %>
                            <li><%= link_to(child.name, edit_admin_category_path(child.id), { tabindex: '-1' })%></li>
                          <% else %>
                            <li><%= link_to(child.name, category_path(child.id), { tabindex: '-1' })%></li>
                          <% end %>
                        <% end %>
                      </ul>
                    </li>
                  <% end%>
                <% end %>
              </ul>
            </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= form_tag search_pins_path, method: :get, class: "navbar-form navbar-left", role: "search" do %>
              <p>
                <%= text_field_tag :search, params[:search], class: "form-control" %>
                <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
              </p>
            <% end %>

            <li><%= link_to "New Pin", new_pin_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to(image_tag(current_user.avatar.url), edit_user_registration_path) %></li>
            <li><%= link_to current_user.username , edit_user_registration_path %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sing In", new_user_session_path %></li>
          </ul>
        <% end %>
    </div>
  </nav>

  <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>
  </div>
  </body>
    <%= yield  %>
  </body>

app/views/pins/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  */
  var disqus_config = function () {
    this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @pin.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://shuttersbank.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/pins/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1> Shuttersbank</h1>
    <p>Beautiful, free photos.</p>
    <p>Gifted by the world’s most generous community of photographers.</p>
  </div>

  <div class="share_box">
    <!--Facebook-->
      <a href="https://www.facebook.com/pages/feccbok/244971538850523"><%= image_tag("facebook.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Twitter-->
      <a href="https://twitter.com/"><%= image_tag("twitter.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Google +-->
      <a href="https://plus.google.com/discover"><%= image_tag("google-plus.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Linkedin-->
      <a href="https://www.linkedin.com/"><%= image_tag("linkedin.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Instagram-->
      <a href="https://www.instagram.com/"><%= image_tag("instagram.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Pinterest-->
      <a href="https://www.pinterest.com/"><%= image_tag("pinterest.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Youtube-->
      <a href="https://www.youtube.com/"><%= image_tag("youtube.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Vkontakte-->
      <a href="https://vk.com/im"><%= image_tag("vk.svg", class: "icon", alt: "Edit Entry") %></a>
    <!--Github-->
      <a href="https://github.com/"><%= image_tag("github-logo.svg", class: "icon", alt: "Edit Entry") %></a>
  </div>
</div>

<div class="tags-field">
  <div class="col-md-8">
      <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

<div class="pins-block">
  <div class="transitions-enabled" id="pins">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url(:thumb)), pin %>
        <div class="panel-body">
          <h2><%= link_to pin.title, pin %></h2>
          <p>
           <small>
              <time><%= pin.created_at.to_date.strftime("%d %B, %Y") %></time>
            </small>
          </p>
          <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
          <p><%= pin.description %></p>

          <p class="user"></p>
          Submitted by
          <%= pin.user.email %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pins/search.html.erb
<div class="pins-block">
  <div class="transitions-enabled" id="pins">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url(:thumb)), pin %>
        <div class="panel-body">
          <h2><%= link_to pin.title, pin %></h2>
          <p>
           <small>
              <time><%= pin.created_at.to_date.strftime("%d %B, %Y") %></time>
            </small>
          </p>
          <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
          <p><%= pin.description %></p>

          <p class="user"></p>
          Submitted by
          <%= pin.user.email %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pins/show.html.erb
  <div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url(:medium) %>
      </div>

      <section class="footer-summary">
        <%= raw @pin.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'btn btn-primary'}.join('') %>
      </section>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p>
          <%= @pin.description %>
        </p>
        <p>
         <small>
            <time><%= @pin.created_at.to_date.strftime("%d %B, %Y") %></time>
          </small>
        </p>
        Submitted by
        <%= @pin.user.email %>
        <p><strong><%= link_to @pin.user.username, user_path(@pin.user.username) %></strong></p>
      </div>

      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <% if @pin.user == current_user %>
            <% end %>
          </div>

          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to Lile_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @pin.get_upvotes.size %>
                </span>
              <% end %>

              <% if current_user.admin? %>
                <%= link_to "Edit", edit_admin_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", admin_pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
              <% elsif user_signed_in? && @pin.user == current_user %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= render 'disqus' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Category</h2>
  <ul class="nav nav-pills nav-stacked">
    <% Category.all.roots.each do |category| %>
      <li class="nav-item">
        <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category))}" %>
        <%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class="subnav nav-pills nav-stacked nested_nav">
  <% categories.each do |category, children| %>
    <li>
      <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category))}" %>
      <%= render 'shared/submenu_categories', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.pins.empty? %>
  <h2>Статей нет</h2>
<% end %>


<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url(:thumb)), pin %>

      <div class="panel-body">
        <h2><%= link_to pin.title, pin %></h2>
        <p>
         <small>
            <time><%= pin.created_at.to_date.strftime("%d %B, %Y") %></time>
          </small>
        </p>
        <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
        <p><%= pin.description %></p>
        <% if pin.user == current_user %>
        <% end %>

        <p class="user"></p>
        Submitted by
        <%= pin.user.email %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div>
  <%= image_tag @user.avatar.url(:thumb) %>
</div>

<h3><%= @user.username %></h3>
<p><%= @user.bio %></p>

<div class="transitions-enabled" id="pins">
  <% @user.pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url(:thumb)), pin %>
      <div class="panel-body">
        <h2>
          <%= link_to pin.title, pin %>
        </h2>

        <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
        <p><%= pin.description %></p>
        <% if pin.user == current_user %>
         <p class="user"></p>
        Submitted by
        <%= pin.user.email %>
          <p></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>